FROM docker-proxy.cdek.ru/cypress/browsers:node-22.21.0-chrome-141.0.7390.107-1-ff-144.0-edge-141.0.3537.92-1

ARG HTTP_PROXY
ARG NO_PROXY

ENV HTTP_PROXY=$HTTP_PROXY
ENV HTTPS_PROXY=$HTTP_PROXY
ENV NO_PROXY=$NO_PROXY

WORKDIR /usr/src/app

COPY package*.json ./
COPY .npmrc ./

RUN npm install
RUN npx playwright install

COPY . .

RUN chmod +x run-tests.sh
RUN chmod +x run-tests-update.sh

CMD ["./run-tests.sh"]
